"""
Smoke tests — performance thresholds for provisioned lab resources.

These tests do not test correctness; they verify that provisioning completed
within expected time bounds and that the S3 API responds within SLA targets.
Both thresholds are intentionally generous — the goal is to catch gross
regressions (hung instances, high-latency regions) not to benchmark.
"""

from __future__ import annotations

import time
import uuid

import boto3
import pytest
from botocore.exceptions import ClientError

pytestmark = pytest.mark.smoke

# ── Thresholds ─────────────────────────────────────────────────────────────────
_LAUNCH_TIME_THRESHOLD_SECONDS: float = 300.0  # 5 minutes: t2.micro boot ceiling
_S3_PUT_LATENCY_THRESHOLD_SECONDS: float = 2.0  # 2 s: generous for cross-region


# ── Tests ──────────────────────────────────────────────────────────────────────

def test_instance_launch_time(resources: dict) -> None:
    """
    EC2 instance must have reached the running state within 300 seconds.

    'launch_time' is written to .cloudforge_state.json by the provisioner
    immediately after the instance_running waiter completes.  If it is
    absent (e.g. the state file was generated by an older run), the test
    is skipped rather than failed.
    """
    launch_time = resources.get("launch_time")

    if launch_time is None:
        pytest.skip(
            "'launch_time' key not present in state file — "
            "re-provision to capture it"
        )

    assert isinstance(launch_time, (int, float)), (
        f"Expected launch_time to be a number, got {type(launch_time).__name__}"
    )

    assert launch_time < _LAUNCH_TIME_THRESHOLD_SECONDS, (
        f"Instance took {launch_time:.1f}s to reach running state "
        f"(threshold: {_LAUNCH_TIME_THRESHOLD_SECONDS:.0f}s).\n"
        f"  This can happen with capacity constraints or slow AMI initialisation.\n"
        f"  Consider retrying in a different AZ or region."
    )


def test_s3_latency(bucket_name: str) -> None:
    """
    A 1 KB S3 PUT must complete within 2 seconds.

    Uses a unique key on every run to avoid false cache hits, and cleans
    up the probe object in a finally block regardless of test outcome.
    Only the PUT is timed — the DELETE is best-effort cleanup and not
    included in the measurement.
    """
    s3 = boto3.client("s3")
    key = f"cloudforge-latency/{uuid.uuid4().hex}.bin"
    payload = b"0" * 1024  # 1 KB — small enough to isolate network overhead

    elapsed: float = 0.0

    try:
        start = time.monotonic()
        s3.put_object(Bucket=bucket_name, Key=key, Body=payload)
        elapsed = time.monotonic() - start
    except ClientError as exc:
        pytest.fail(
            f"Latency probe PUT to s3://{bucket_name}/{key} failed: "
            f"{exc.response['Error']['Code']}"
        )
    finally:
        # Best-effort cleanup — do not let a delete failure hide the real result.
        try:
            s3.delete_object(Bucket=bucket_name, Key=key)
        except ClientError:
            pass

    assert elapsed < _S3_PUT_LATENCY_THRESHOLD_SECONDS, (
        f"S3 PUT latency {elapsed:.3f}s exceeds threshold "
        f"{_S3_PUT_LATENCY_THRESHOLD_SECONDS:.1f}s.\n"
        f"  Bucket : {bucket_name}\n"
        f"  Payload: {len(payload)} bytes\n"
        f"  This may indicate high network latency to the bucket's region "
        f"or an AWS-side throttle."
    )
